### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by BrianGilbert** [StephenOTT/GitLab-Time-Tracking#15]
and will i end up having upgrade issues if I was to use it with the omnibus package of Gitlab Community Edition?

**Comment by StephenOTT** [comment]
Hey. 
It is not tied to the omnibus package.  It is a Sinatra App that stores data in MongoDB.
Its still active as in if there are some requests I will work on them when i can, and I am happy to take pull requests.

Essentially this is a standalone app that connects to a GitLab instance using the GitLab REST API.

**Comment by StephenOTT** [comment]
Whats your use case?  May be able to point you in a better direction or set you up using this Repo.

**Comment by BrianGilbert** [comment]
Does it handle tracking of time that isn't based on an issue?

We're trying to find a better way to manage time tracking and most of our work revolves around gitlab, apart from consulting time before we get to using gitlab.

**Comment by StephenOTT** [comment]
Yes it does.  Look at the Readme.  The point of this app is to really allow you to store your time tracking data directly in GitLab rather than holding the data in a third party DB.  MongoDB is only used to store snapshots of the time tracking data for audit purposes.

You can download the data as a XLSX file and modify in excel or any spreadsheet software.
Also know that this was created a bit as a proof of concept app.  So if you are interested, give it a try, and I am happy to modify/enhance as required.

**Comment by StephenOTT** [comment]
> Does it handle tracking of time that isn't based on an issue?

To give you a little more detail take a look at the following: https://github.com/StephenOTT/GitHub-Time-Tracking
I don't believe i implemented the commits tracking, but it can be easily added.  Look at readme of the GitHub-Time-Tracking Repo and you can see everything.

**Comment by StephenOTT** [comment]
@BrianGilbert you may also want to look at tools like: https://github.com/klokantech/github-time-tracking which is a harvest integration with Chrome.

GitLab-Time-Tracking is really about finding a way to keep the time tracking data directly in GitLab rather than the traditional solutions which focused on storing the time-tracking data outside of Github and only holding a link between the time tracking data and the issue or commit.

**Comment by BrianGilbert** [comment]
@StephenOTT thanks, we just started using Toggl, I think it will meet our needs with less infrastructure changes.
